CREATE TABLE `cms_discovery_goods_inventory` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `main_title` varchar(200) DEFAULT NULL COMMENT '主标题',
  `sub_title` varchar(300) DEFAULT NULL COMMENT '副标题',
  `description` varchar(500) DEFAULT NULL COMMENT '描述',
  `img` varchar(255) DEFAULT NULL COMMENT '封面图',
  `status` tinyint(4) DEFAULT NULL COMMENT '状态:1,上线;',
  `submit_time` datetime DEFAULT NULL COMMENT '发布者最后一次提交时间',
  `publish_time` datetime DEFAULT NULL COMMENT '最后一次上线时间',
  `off_reason` varchar(300) DEFAULT NULL COMMENT '下线原因',
  `top` tinyint(4) DEFAULT '0' COMMENT '是否置顶，1为置顶，0为非置顶',
  `top_order` tinyint(4) DEFAULT '4' COMMENT '置顶顺序，最多3篇置顶',
  `top_start_time` datetime DEFAULT NULL COMMENT '置顶开始时间',
  `top_end_time` datetime DEFAULT NULL COMMENT '置顶结束时间',
  `operator` varchar(50) DEFAULT NULL COMMENT '操作人',
  `modified` datetime DEFAULT NULL COMMENT 'cms修改时间',
  `position` tinyint(4) DEFAULT NULL COMMENT '0为清单频道，1为发现好货;',
  PRIMARY KEY (`id`),
  KEY `status_index` (`status`) ,
  KEY `position_index` (`position`) ,
  KEY `top_index` (`top`) 
) ENGINE=InnoDB AUTO_INCREMENT=57 DEFAULT CHARSET=utf8 COMMENT='清单';